databases:
  - name: postgres
    databaseName: postgres_7cxr
    user: postgres_7cxr_user

services:
  - type: web
    name: RentYourCar
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false