---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cars/{id}":
    parameters:
    - name: id
      in: path
      description: ID of the car
      required: true
      schema:
        type: integer
    - name: Authorization
      in: header
      required: true
      schema:
        type: string
    get:
      summary: Retrieves a car by ID
      tags:
      - Cars
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: car found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  make:
                    type: string
                  model:
                    type: string
                  year:
                    type: integer
                  price:
                    type: integer
                  user_id:
                    type: integer
                  image:
                    type: string
                required:
                - id
                - make
                - model
                - year
                - price
                - user_id
                - image
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
